In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("ci_main.csv")
df.head()

,collection_id,captcha_image,response,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,mode
0,2.025030e+19,3q1ax.jpg,3Q1AX,6813,True,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",human
1,2.025030e+19,1FicN.jpg,1FiDN,10161,False,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",human
2,2.025030e+19,1FicN.jpg,1FicN,7899,True,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",human
3,2.025030e+19,3Ssqt.jpg,3SSQT,7379,True,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",human
4,2.025030e+19,3tClm.jpg,3tcsd,5965,False,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",human

In [4]:
df["actual"] = df["captcha_image"].apply(lambda x: x.split("/")[-1].split(".")[0])
df.head()

,collection_id,captcha_image,response,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,mode,actual
0,2.025030e+19,3q1ax.jpg,3Q1AX,6813,True,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",human,3q1ax
1,2.025030e+19,1FicN.jpg,1FiDN,10161,False,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",human,1FicN
2,2.025030e+19,1FicN.jpg,1FicN,7899,True,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",human,1FicN
3,2.025030e+19,3Ssqt.jpg,3SSQT,7379,True,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",human,3Ssqt
4,2.025030e+19,3tClm.jpg,3tcsd,5965,False,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",human,3tClm

In [5]:
df.drop(columns=["collection_id", "captcha_image", "mode"], inplace=True)
df.head()

,response,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual
0,3Q1AX,6813,True,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax
1,1FiDN,10161,False,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN
2,1FicN,7899,True,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN
3,3SSQT,7379,True,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt
4,3tcsd,5965,False,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm

In [6]:
df["is_correct"] = np.where(df["actual"] == df["response"], 1, 0)
df.head()

,response,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual
0,3Q1AX,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax
1,1FiDN,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN
2,1FicN,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN
3,3SSQT,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt
4,3tcsd,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm

In [7]:
df = df[[col for col in df.columns if col != 'response'] + ['response']]
df.head()

,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual,response
0,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax,3Q1AX
1,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN,1FiDN
2,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN,1FicN
3,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt,3SSQT
4,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm,3tcsd

In [8]:
df = df.dropna()
df.head()

,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual,response
0,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax,3Q1AX
1,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN,1FiDN
2,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN,1FicN
3,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt,3SSQT
4,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm,3tcsd

In [9]:
df.drop_duplicates(inplace=True)
df.head()

,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual,response
0,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax,3Q1AX
1,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN,1FiDN
2,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN,1FicN
3,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt,3SSQT
4,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm,3tcsd

In [10]:
df.shape

(2103, 8)

In [11]:
df.to_csv("ci_main_cleaned.csv", index=False)
df.head()

,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual,response
0,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax,3Q1AX
1,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN,1FiDN
2,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN,1FicN
3,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt,3SSQT
4,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm,3tcsd

In [12]:
import ast
df["mouse_movements"] = df["mouse_movements"].apply(ast.literal_eval)
df = df[df["mouse_movements"].apply(lambda x: len(x) > 10)].reset_index(drop=True)

In [13]:
df.head()

,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual,response
0,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax,3Q1AX
1,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN,1FiDN
2,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN,1FicN
3,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt,3SSQT
4,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm,3tcsd

In [14]:
df.to_csv("ci_main_cleaned.csv", index=False)
df.head()

,time_taken,is_correct,attempts,key_presses,backspace_presses,mouse_movements,actual,response
0,6813,0,1,8,0,"[{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...",3q1ax,3Q1AX
1,10161,0,1,15,3,"[{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...",1FicN,1FiDN
2,7899,1,2,9,1,"[{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...",1FicN,1FicN
3,7379,0,1,7,0,"[{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...",3Ssqt,3SSQT
4,5965,0,1,5,0,"[{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...",3tClm,3tcsd

In [15]:
df.shape

(1776, 8)

In [16]:
print(df.head())

   time_taken  is_correct  attempts  key_presses  backspace_presses  \
0        6813           0         1            8                  0
1       10161           0         1           15                  3
2        7899           1         2            9                  1
3        7379           0         1            7                  0
4        5965           0         1            5                  0

                                     mouse_movements actual response
0  [{'x': 692, 'y': 591}, {'x': 690, 'y': 575}, {...  3q1ax    3Q1AX
1  [{'x': 796, 'y': 346}, {'x': 796, 'y': 347}, {...  1FicN    1FiDN
2  [{'x': 784, 'y': 447}, {'x': 783, 'y': 445}, {...  1FicN    1FicN
3  [{'x': 816, 'y': 364}, {'x': 816, 'y': 366}, {...  3Ssqt    3SSQT
4  [{'x': 851, 'y': 353}, {'x': 848, 'y': 357}, {...  3tClm    3tcsd

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1776 entries, 0 to 1775
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time_taken         1776 non-null   int64
 1   is_correct         1776 non-null   int64
 2   attempts           1776 non-null   int64
 3   key_presses        1776 non-null   int64
 4   backspace_presses  1776 non-null   int64
 5   mouse_movements    1776 non-null   object
 6   actual             1776 non-null   object
 7   response           1776 non-null   object
dtypes: int64(5), object(3)
memory usage: 111.1+ KB